heat_template_version: 2013-05-23

description: Deploy a CoreOS cluster that operates a Kubernetes cluster

parameters:
  kubernetes-master-count:
    description: Number of CoreOS machines to deploy as Kubernetes Master
    type: number
    default: 1
    constraints:
    - range:
        min: 1
        max: 1
      description: Must be between 1 and 1 servers.
  kubernetes-minion-count:
    description: Number of CoreOS machines to deploy as Kubernetes Minion
    type: number
    default: 3
    constraints:
    - range:
        min: 2
        max: 12
      description: Must be between 2 and 12 servers.
  key-name:
    type: string
    description: Name of key-pair to be used for compute instance
  flavor:
    type: string
    default: 4 GB Performance
    constraints:
    - allowed_values:
      - 2 GB Performance
      - 4 GB Performance
      - 8 GB Performance
      - 15 GB Performance
      - 30 GB Performance
      description: |
        Must be a valid Rackspace Cloud Server flavor for the region you have
        selected to deploy into.
  coreos-image:
    type: string
    description: Rackspace Cloud Servers CoreOS Alpha (423.0.0) UUID
    default: "e90d62b9-0f01-4da9-9e06-79b8ddf42a70"
  git-repo:
    type: string
    description: Public git repo url
    default: "https://github.com/metral/corekube.git"
  git-branch:
    type: string
    description: Git repo branch
    default: "master"

resources:

  coreos-cluster-uuid:
    type: OS::Heat::RandomString

  priv_network:
    type: Rackspace::Cloud::Network
    properties:
      label: kubernetes
      cidr: 192.168.3.0/24

  discovery:
    type: OS::Nova::Server
    properties:
      key_name: { get_param: key-name }
      image: { get_param: coreos-image }
      flavor: { get_param: flavor }
      name: "discovery"
      user_data_format: RAW
      config_drive: "true"
      user_data: |
        #cloud-config

        coreos:
          update:
            group: alpha
            reboot-strategy: off

          units:
            - name: private-discovery.service
              command: start
              content: |
                [Unit]
                After=network-online.target
                Requires=network-online.target

                [Service]
                ExecStart=/usr/bin/docker run -d --name discovery -p 4001:4001 -p 7001:7001 coreos/etcd

  overlord:
    type: OS::Nova::Server
    properties:
      key_name: { get_param: key-name }
      image: { get_param: coreos-image }
      flavor: { get_param: flavor }
      name: "overlord"
      user_data_format: RAW
      config_drive: "true"
      user_data:
        str_replace:
          template: |
            #cloud-config

            write_files:
              - content: |
                  StrictHostKeyChecking no
                  UserKnownHostsFile /dev/null
                  LogLevel QUIET
                path: /root/.ssh/config
                permissions: '0644'
            coreos:
              etcd:
                name: overlord
                discovery: http://%discovery%:4001/v2/keys/_etcd/registry/%uuid%
                addr: $private_ipv4:4001
                peer-addr: $private_ipv4:7001

              fleet:
                public-ip: $private_ipv4
                metadata: kubernetes_role=overlord
                  
              update:
                group: alpha
                reboot-strategy: off

              units:
                - name: etcd.service
                  command: start
                - name: fleet.socket
                  command: start
                  content: |
                    [Socket]
                    # Talk to the API over a Unix domain socket (default)
                    ListenStream=/var/run/fleet.sock
                    # Talk to the API over an exposed port, uncomment to enable and choose a port
                    ListenStream=10001
                    Environment=FLEET_PUBLIC_IP=$private_ipv4
                    Environment=FLEET_METADATA=kubernetes_role=overlord
                    Service=fleet.service

                    [Install]
                    WantedBy=sockets.target
                - name: setup-kubernetes.service
                  command: start
                  content: |
                    [Unit]
                    After=network-online.target
                    Requires=network-online.target

                    [Service]
                    WorkingDirectory=/root
                    Environment="DIR=corekube"
                    ExecStartPre=/usr/bin/rm -rf $DIR
                    ExecStartPre=/usr/bin/git clone -b %branch% %repo%
                    ExecStart=/usr/bin/bash ${DIR}/build_run.sh %branch% %master_count% %minion_count% 1
          params:
            "%discovery%": { get_attr: [discovery, networks, private, 0] }
            "%uuid%": { get_attr: [coreos-cluster-uuid, value] }
            "%master_count%": { get_param: kubernetes-master-count }
            "%minion_count%": { get_param: kubernetes-minion-count }
            "%repo%": { get_param: git-repo }
            "%branch%": { get_param: git-branch }

  master_machines:
    type: "OS::Heat::ResourceGroup"
    properties:
      count: { get_param: kubernetes-master-count }
      resource_def:
        type: OS::Nova::Server
        properties:
          key_name: { get_param: key-name }
          image: { get_param: coreos-image }
          flavor: { get_param: flavor }
          name: kubernetes-master-%index%
          networks:
          - uuid: "00000000-0000-0000-0000-000000000000"
          - uuid: "11111111-1111-1111-1111-111111111111"
          - uuid: { get_resource: priv_network }
          user_data_format: RAW
          config_drive: "true"
          user_data:
            str_replace:
              template: |
                #cloud-config

                coreos:
                  etcd:
                    name: kubernetes-master-%index%
                    discovery: http://%discovery%:4001/v2/keys/_etcd/registry/%uuid%
                    addr: $private_ipv4:4001
                    peer-addr: $private_ipv4:7001

                  fleet:
                    public-ip: $private_ipv4
                    metadata: kubernetes_role=master

                  update:
                    group: alpha
                    reboot-strategy: off

                  units:
                    - name: etcd.service
                      command: start
                    - name: fleet.service
                      command: start
                    - name: cbr0.netdev
                      command: start
                      content: |
                        [NetDev]
                        Kind=bridge
                        Name=cbr0
                    - name: cbr0.network
                      command: start
                      content: |
                        [Match]
                        Name=cbr0

                        [Network]
                        Address=10.244.%index%.1/24

                        [Route]
                        Destination=10.244.0.0/15
                        Gateway=0.0.0.0
                    - name: vxlan0.netdev
                      command: start
                      content: |
                        [NetDev]
                        Kind=vxlan
                        Name=vxlan0

                        [VXLAN]
                        Id=1
                        Group=224.0.0.1
                    - name: 49-eth2.network
                      command: start
                      content: |
                        [Match]
                        Name=eth2

                        [Network]
                        VXLAN=vxlan0
                    - name: vxlan0.network
                      command: start
                      content: |
                        [Match]
                        Name=vxlan0

                        [Network]
                        Bridge=cbr0
                    - name: docker.service
                      command: start
                      content: |
                        [Unit]
                        After=network.target
                        Description=Docker Application Container Engine
                        Documentation=http://docs.docker.io

                        [Service]
                        ExecStartPre=/bin/mount --make-rprivate /
                        ExecStart=/usr/bin/docker -d -s=btrfs -H fd:// -b cbr0

                        [Install]
                        WantedBy=multi-user.target
              params:
                "%discovery%": { get_attr: [discovery, networks, private, 0] }
                "%uuid%": { get_attr: [coreos-cluster-uuid, value] }

  minion_machines:
    type: "OS::Heat::ResourceGroup"
    properties:
      count: { get_param: kubernetes-minion-count }
      resource_def:
        type: OS::Nova::Server
        properties:
          key_name: { get_param: key-name }
          image: { get_param: coreos-image }
          flavor: { get_param: flavor }
          name: kubernetes-minion-%index%
          networks:
          - uuid: "00000000-0000-0000-0000-000000000000"
          - uuid: "11111111-1111-1111-1111-111111111111"
          - uuid: { get_resource: priv_network }
          user_data_format: RAW
          config_drive: "true"
          user_data:
            str_replace:
              template: |
                #cloud-config

                coreos:
                  etcd:
                    name: kubernetes-minion-%index%
                    discovery: http://%discovery%:4001/v2/keys/_etcd/registry/%uuid%
                    addr: $private_ipv4:4001
                    peer-addr: $private_ipv4:7001

                  fleet:
                    public-ip: $private_ipv4
                    metadata: kubernetes_role=minion

                  update:
                    group: alpha
                    reboot-strategy: off
                      
                  units:
                    - name: etcd.service
                      command: start
                    - name: fleet.service
                      command: start
                    - name: cbr0.netdev
                      command: start
                      content: |
                        [NetDev]
                        Kind=bridge
                        Name=cbr0
                    - name: cbr0.network
                      command: start
                      content: |
                        [Match]
                        Name=cbr0

                        [Network]
                        Address=10.245.%index%.1/24

                        [Route]
                        Destination=10.244.0.0/15
                        Gateway=0.0.0.0
                    - name: vxlan0.netdev
                      command: start
                      content: |
                        [NetDev]
                        Kind=vxlan
                        Name=vxlan0

                        [VXLAN]
                        Id=1
                        Group=224.0.0.1
                    - name: 49-eth2.network
                      command: start
                      content: |
                        [Match]
                        Name=eth2

                        [Network]
                        VXLAN=vxlan0
                    - name: vxlan0.network
                      command: start
                      content: |
                        [Match]
                        Name=vxlan0

                        [Network]
                        Bridge=cbr0
                    - name: docker.service
                      command: start
                      content: |
                        [Unit]
                        After=network.target
                        Description=Docker Application Container Engine
                        Documentation=http://docs.docker.io

                        [Service]
                        ExecStartPre=/bin/mount --make-rprivate /
                        ExecStart=/usr/bin/docker -d -s=btrfs -H fd:// -b cbr0

                        [Install]
                        WantedBy=multi-user.target
              params:
                "%discovery%": { get_attr: [discovery, networks, private, 0] }
                "%uuid%": { get_attr: [coreos-cluster-uuid, value] }
